# This is the Jenkins ci variant of the .github/labler.yaml

"CI-iot-samples-test":
  - "**/*"
  - !"softdevice_controller/include/**/*"
  - !"softdevice_controller/lib/**/*"
  - !"mpsl/include/**/*"
  - !"mpsl/lib/**/*"

"CI-iot-libraries-test":
  - "**/*"
  - !"softdevice_controller/include/**/*"
  - !"softdevice_controller/lib/**/*"
  - !"mpsl/include/**/*"
  - !"mpsl/lib/**/*"

"CI-lwm2m-test":
  - "**/*"
  - !"softdevice_controller/include/**/*"
  - !"softdevice_controller/lib/**/*"
  - !"mpsl/include/**/*"
  - !"mpsl/lib/**/*"

"CI-boot-dfu-test":
  - "**/*"

"CI-tfm-test":
  - "**/*"
  - !"softdevice_controller/include/**/*"
  - !"softdevice_controller/lib/**/*"
  - !"mpsl/include/**/*"
  - !"mpsl/lib/**/*"

"CI-ble-test":
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"

"CI-mesh-test":
  - "**/*"

"CI-zigbee-test":
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"
  - "nrf_802154/driver/**/*"
  - "nrf_802154/serialization/**/*"
  - "nrf_802154/sl/**/*"
  - any:
    - "zboss/**/*"
    - "!zboss/*.rst"
    - "!zboss/doc/**/*"

"CI-thingy91-test":
  - "**/*"

"CI-desktop-test":
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"

"CI-crypto-test":
  - "**/*"
  - !"softdevice_controller/include/**/*"
  - !"softdevice_controller/lib/**/*"
  - !"mpsl/include/**/*"
  - !"mpsl/lib/**/*"

"CI-rs-test":
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"

"CI-homekit-test":
  - "crypto/**/*"
  - "openthread/**/*"
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"
  - "nfc/**/*"
  - "nrf_802154/driver/**/*"
  - "nrf_802154/serialization/**/*"
  - "nrf_802154/sl/**/*"
  - "nrf_security/**/*"

"CI-thread-test":
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"
  - "nrf_802154/driver/**/*"
  - "nrf_802154/serialization/**/*"
  - "nrf_802154/sl/**/*"
  - "crypto/**/*"
  - any:
    - "openthread/**/*"
    - "!openthread/*.rst"
    - "!openthread/doc/**/*"

"CI-nfc-test":
  - "**/*"
  - !"softdevice_controller/include/**/*"
  - !"softdevice_controller/lib/**/*"
  - !"mpsl/include/**/*"
  - !"mpsl/lib/**/*"

"CI-matter-test":
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"

"CI-find-my-test":
  - "**/*"

"CI-gazell-test":
  - "**/*"

"CI-rpc-test":
  - "**/*"

"CI-modemshell-test":
  - "**/*"
  - !"softdevice_controller/include/**/*"
  - !"softdevice_controller/lib/**/*"
  - !"mpsl/include/**/*"
  - !"mpsl/lib/**/*"

"CI-positioning-test":
  - "**/*"
  - !"softdevice_controller/include/**/*"
  - !"softdevice_controller/lib/**/*"
  - !"mpsl/include/**/*"
  - !"mpsl/lib/**/*"
