# This is the Jenkins ci variant of the .github/labler.yaml
"CI-iot-zephyr-lwm2m-test":
  - any:
      - "nrf_modem/**/*"
      - !"nrf_modem/doc/**/*"
      - !"nrf_modem/*.rst"
  - "nrf_security/src/**/*"
  - "crypto/nrf_oberon/**/*"

"CI-iot-samples-test":
  - any:
      - "nrf_modem/**/*"
      - !"nrf_modem/doc/**/*"
      - !"nrf_modem/*.rst"

"CI-iot-libraries-test":
  - any:
      - "nrf_modem/**/*"
      - !"nrf_modem/doc/**/*"
      - !"nrf_modem/*.rst"

"CI-lwm2m-test":
  - any:
      - "nrf_modem/**/*"
      - !"nrf_modem/doc/**/*"
      - !"nrf_modem/*.rst"

"CI-tfm-test":
  - "nrf_security/**/*"
  - any:
      - "crypto/**/*"
      - !"crypto/doc/**/*"
      - !"crypto/*.rst"

"CI-ble-test":
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"

"CI-mesh-test":
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"

"CI-zigbee-test":
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"
  - "nrf_802154/driver/**/*"
  - "nrf_802154/serialization/**/*"
  - "nrf_802154/sl/**/*"
  - any:
    - "zboss/**/*"
    - "!zboss/*.rst"
    - "!zboss/doc/**/*"

"CI-desktop-test":
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"

"CI-crypto-test":
  - "nrf_security/**/*"
  - any:
      - "crypto/**/*"
      - !"crypto/doc/**/*"
      - !"crypto/*.rst"

"CI-rs-test":
  - "mpsl/CMakeLists.txt"
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"
  - "softdevice_controller/CMakeLists.txt"
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"
  - "nrf_802154/**/*"

"CI-fem-test":
  - "mpsl/CMakeLists.txt"
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"
  - "softdevice_controller/CMakeLists.txt"
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"
  - "nrf_802154/**/*"

"CI-homekit-test":
  - "openthread/**/*"
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"
  - "nrf_802154/driver/**/*"
  - "nrf_802154/serialization/**/*"
  - "nrf_802154/sl/**/*"
  - "nrf_security/**/*"
  - any:
      - "crypto/**/*"
      - !"crypto/doc/**/*"
      - !"crypto/*.rst"

"CI-thread-test":
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"
  - "nrf_802154/driver/**/*"
  - "nrf_802154/serialization/**/*"
  - "nrf_802154/sl/**/*"
  - any:
      - "crypto/**/*"
      - !"crypto/doc/**/*"
      - !"crypto/*.rst"
  - any:
    - "openthread/**/*"
    - "!openthread/*.rst"
    - "!openthread/doc/**/*"

"CI-nfc-test":
  - any:
      - "nfc/**/*"
      - !"nfc/doc/**/*"
      - !"nfc/*.rst"

"CI-matter-test":
  - "openthread/**/*"
  - "softdevice_controller/include/**/*"
  - "softdevice_controller/lib/**/*"
  - "mpsl/include/**/*"
  - "mpsl/lib/**/*"
  - "nrf_802154/driver/**/*"
  - "nrf_802154/serialization/**/*"
  - "nrf_802154/sl/**/*"
  - "nrf_security/**/*"
  - any:
      - "crypto/**/*"
      - !"crypto/doc/**/*"
      - !"crypto/*.rst"

"CI-find-my-test":
  - "nrf_security/**/*"
  - "softdevice_controller/**/*"
  - any:
      - "nfc/**/*"
      - !"nfc/doc/**/*"
      - !"nfc/*.rst"
  - any:
      - "crypto/**/*"
      - !"crypto/doc/**/*"
      - !"crypto/*.rst"

"CI-gazell-test":
  - "gzll/CMakeLists.txt"
  - "gzll/lib/**/*"
  - "gzll/include/**/*"

"CI-rpc-test":
  - "nrf_rpc/**/*"

"CI-modemshell-test":
  - any:
      - "nrf_modem/**/*"
      - !"nrf_modem/doc/**/*"
      - !"nrf_modem/*.rst"

"CI-positioning-test":
  - any:
      - "nrf_modem/**/*"
      - !"nrf_modem/doc/**/*"
      - !"nrf_modem/*.rst"

"CI-cloud-test":
  - any:
      - "nrf_modem/**/*"
      - !"nrf_modem/doc/**/*"
      - !"nrf_modem/*.rst"
  - "nrf_security/**/*"
  - "nrf_rpc/**/*"
  - any:
      - "crypto/**/*"
      - !"crypto/doc/**/*"
      - !"crypto/*.rst"

"CI-wifi":
  - "nrf_security/**/*"
  - any:
      - "crypto/**/*"
      - !"crypto/doc/**/*"
      - !"crypto/*.rst"
