# This is the Jenkins ci variant of the .github/labler.yaml

CI-ble-test:
  - 'softdevice_controller/include/**/*'
  - 'softdevice_controller/lib/**/*'
  - 'mpsl/include/**/*'
  - 'mpsl/lib/**/*'

CI-zigbee-test:
  - 'softdevice_controller/include/**/*'
  - 'softdevice_controller/lib/**/*'
  - 'mpsl/include/**/*'
  - 'mpsl/lib/**/*'

CI-desktop-test:
  - 'softdevice_controller/include/**/*'
  - 'softdevice_controller/lib/**/*'

CI-rs-test:
  - 'mpsl/include/**/*'
  - 'mpsl/lib/**/*'

CI-homekit-test:
  - 'softdevice_controller/include/**/*'
  - 'softdevice_controller/lib/**/*'
  - 'mpsl/include/**/*'
  - 'mpsl/lib/**/*'

CI-thread-test:
  - 'mpsl/include/**/*'
  - 'mpsl/lib/**/*'

CI-matter-test:
  - 'mpsl/include/**/*'
  - 'mpsl/lib/**/*'
