/*
 * Copyright (c) 2021 Nordic Semiconductor
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#if defined(PSA_CRYPTO_DRIVER_HAS_CIPHER_SUPPORT_OBERON)
#define PSA_NEED_OBERON_CIPHER_DRIVER
#define PSA_NEED_OBERON_CHACHA20
#endif

#if defined(PSA_CRYPTO_DRIVER_HAS_AEAD_SUPPORT_OBERON)
#define PSA_NEED_OBERON_AEAD_DRIVER
#endif

#if defined(PSA_CRYPTO_DRIVER_HAS_HASH_SUPPORT_OBERON)
#define PSA_NEED_OBERON_HASH_DRIVER
#endif

#if defined(PSA_CRYPTO_DRIVER_HAS_ASYM_SIGN_SUPPORT_OBERON)
#define PSA_NEED_OBERON_ASYM_SIGN_SUPPORT
#endif

#if defined(PSA_CRYPTO_DRIVER_HAS_ECC_SUPPORT_OBERON)
#define PSA_NEED_OBERON_ECC_SUPPORT
#endif

#if defined(PSA_CRYPTO_DRIVER_HAS_ACCEL_KEY_TYPES_OBERON)
#define PSA_NEED_OBERON_ACCEL_KEY_TYPES
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_CBC_NO_PADDING_OBERON)
#define PSA_NEED_OBERON_AES_CBC_NO_PADDING
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_CBC_PKCS7_OBERON)
#define PSA_NEED_OBERON_AES_CBC_PKCS7
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_CCM_OBERON)
#define PSA_NEED_OBERON_AES_CCM
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_CMAC_OBERON)
#define PSA_NEED_OBERON_CMAC
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_CHACHA20_POLY1305_OBERON)
#define PSA_NEED_OBERON_CHACHA20_POLY1305
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_CMAC_OBERON)
#define PSA_NEED_OBERON_CMAC
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_CTR_OBERON)
#define PSA_NEED_OBERON_AES_CTR
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_DETERMINISTIC_ECDSA_OBERON)
#define PSA_NEED_OBERON_DETERMINISTIC_ECDSA
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_ECB_NO_PADDING_OBERON)
#define PSA_NEED_OBERON_AES_ECB_NO_PADDING
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_ECDH_OBERON)
#define PSA_NEED_OBERON_ECDH_DRIVER
#define PSA_NEED_OBERON_ECDH_P224
#define PSA_NEED_OBERON_ECDH_P256
#define PSA_NEED_OBERON_ECDH_P384
#define PSA_NEED_OBERON_ECDH_X25519
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_ECDSA_OBERON)
#define PSA_NEED_OBERON_ECDSA_DRIVER
#define PSA_NEED_OBERON_ECDSA_P224
#define PSA_NEED_OBERON_ECDSA_P256
#define PSA_NEED_OBERON_ECDSA_P384
#define PSA_NEED_OBERON_ECDSA_ED25519
#define PSA_NEED_OBERON_DETERMINISTIC_ECDSA
#define PSA_NEED_OBERON_RANDOMIZED_ECDSA
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_GCM_OBERON)
#define PSA_NEED_OBERON_AES_GCM
#endif

#if defined(PSA_CRYPTO_DRIVER_HAS_KDF_SUPPORT_OBERON)
#define PSA_NEED_OBERON_KDF_DRIVER
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_HKDF_OBERON)
#define PSA_NEED_OBERON_HKDF
#define PSA_NEED_OBERON_HKDF_EXTRACT
#define PSA_NEED_OBERON_HKDF_EXPAND
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_HMAC_OBERON)
#define PSA_NEED_OBERON_HMAC
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_SHA_1_OBERON)
#define PSA_NEED_OBERON_SHA_1
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_SHA_224_OBERON)
#define PSA_NEED_OBERON_SHA_224
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_SHA_256_OBERON)
#define PSA_NEED_OBERON_SHA_256
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_SHA_384_OBERON)
#define PSA_NEED_OBERON_SHA_384
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_SHA_512_OBERON)
#define PSA_NEED_OBERON_SHA_512
#endif

#if defined(PSA_CRYPTO_DRIVER_ECC_SECP_R1_224_OBERON)
#define PSA_NEED_OBERON_KEY_PAIR_DRIVER 1
#define PSA_NEED_OBERON_KEY_PAIR_P224 1
#define PSA_NEED_OBERON_KEY_PAIR_SECP 1
#endif

#if defined(PSA_CRYPTO_DRIVER_ECC_SECP_R1_256_OBERON)
#define PSA_NEED_OBERON_KEY_PAIR_DRIVER 1
#define PSA_NEED_OBERON_KEY_PAIR_P256 1
#define PSA_NEED_OBERON_KEY_PAIR_SECP 1
#endif

#if defined(PSA_CRYPTO_DRIVER_ECC_SECP_R1_384_OBERON)
#define PSA_NEED_OBERON_KEY_PAIR_DRIVER                        1
#define PSA_NEED_OBERON_KEY_PAIR_P384                          1
#define PSA_NEED_OBERON_KEY_PAIR_SECP                          1
#endif

#if defined(PSA_CRYPTO_DRIVER_ECC_MONTGOMERY_255_OBERON)
#define PSA_NEED_OBERON_KEY_PAIR_DRIVER 1
#define PSA_NEED_OBERON_KEY_PAIR_X25519 1
#define PSA_NEED_OBERON_KEY_PAIR_25519 1
#endif

#if defined(PSA_CRYPTO_DRIVER_ECC_TWISTED_EDWARDS_255_OBERON)
#define PSA_NEED_OBERON_KEY_PAIR_DRIVER 1
#define PSA_NEED_OBERON_KEY_PAIR_ED25519 1
#endif

#if defined(PSA_CRYPTO_DRIVER_HAS_RSA_SUPPORT_OBERON)
#define PSA_NEED_OBERON_RSA_DRIVER                             1
#define PSA_NEED_OBERON_RSA_KEY_SIZE_1536                      1
#define PSA_NEED_OBERON_RSA_KEY_SIZE_2048                      1
#define PSA_NEED_OBERON_RSA_KEY_SIZE_3072                      1
/* Increasing this value has consequences on callers stack usage. */
#define PSA_MAX_RSA_KEY_BITS 3072
#endif

#if defined(PSA_CRYPTO_DRIVER_HAS_RSA_CRYPT_SUPPORT_OBERON)
#define PSA_NEED_OBERON_RSA_CRYPT                              1
#endif

#if defined(PSA_CRYPTO_DRIVER_HAS_RSA_SIGN_SUPPORT_OBERON)
#define PSA_NEED_OBERON_RSA_SIGN                               1
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_RSA_PKCS1V15_CRYPT_OBERON)
#define PSA_NEED_OBERON_RSA_PKCS1V15_CRYPT                     1
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_RSA_PKCS1V15_SIGN_OBERON)
#define PSA_NEED_OBERON_RSA_PKCS1V15_SIGN                      1
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_RSA_OAEP_OBERON)
#define PSA_NEED_OBERON_RSA_OAEP                               1
#endif

#if defined(PSA_CRYPTO_DRIVER_ALG_RSA_PSS_OBERON)
#define PSA_NEED_OBERON_RSA_PSS                                1
#endif
