/*
 * Copyright (c) 2020 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-BSD-5-Clause-Nordic
 */
#ifndef ZBOSS_BUILD_INFO_H__
#define ZBOSS_BUILD_INFO_H__

/**
 * This is an autogenerated file.
 * Please use release scripts to update it's contents.
 *
 * Repositories:
 * platform_ncs       090fb637f0a62ccbe651d5a3307c0ea31d97dacb https://bitbucket-zoi.dsr-corporation.com/scm/ZOI/platform_ncs.git
 * zboss-stack-src    4c971a7c222064f81641184c25a0b7d70c739802 https://bitbucket-zoi.dsr-corporation.com/scm/zoi/zboss_stable
 * zboss-stack-doc    639a0cda809df2ac8289828239c267fc4d4feae4 https://bitbucket-zoi.dsr-corporation.com/scm/zoi/zboss_doc
 * nrf                14ee6d1f52124fd1538421ef09e780af735d0234 https://github.com/nrfconnect/sdk-nrf
 * zephyr             247f9af846a29c4ffcefccb24b2a2348a2e9257f https://github.com/nrfconnect/sdk-zephyr
 * mcuboot            50eec26a462d8cbc171dbbdca623979294a6227b https://github.com/nrfconnect/sdk-mcuboot
 * mcumgr             cfe5eb98a9493017448846fd1a44a9340bd0a22f https://github.com/nrfconnect/sdk-mcumgr
 * nrfxlib            721f19da2be9e2848e507b9a12b6a504e227f2b7 https://github.com/nrfconnect/sdk-nrfxlib
 * cmock              c243b9a7a7b3c471023193992b46cf1bd1910450 https://github.com/ThrowTheSwitch/cmock
 * unity              031f3bbe45f8adf504ca3d13e6f093869920b091 https://github.com/ThrowTheSwitch/unity
 * mbedtls-nrf        2a1d9332d55d1270084232e42df08fdb08129f1b https://github.com/ARMmbed/mbedtls
 * nanopb             df0e92f474f9cca704fe2b31483f0b4d1b1715a4 https://github.com/nanopb/nanopb
 * Alexa-Gadgets-Embedded-Sample-Code face92d8c62184832793f518bb1f19379538c5c1 https://github.com/alexa/Alexa-Gadgets-Embedded-Sample-Code
 * cmsis              542b2296e6d515b265e25c6b7208e8fea3014f90 https://github.com/zephyrproject-rtos/cmsis
 * canopennode        5c6b0566d56264efd4bf23ed58bc7cb8b32fe063 https://github.com/zephyrproject-rtos/canopennode
 * ci-tools           da9a2df574094f52d87a03f6393928bdc7dce17c https://github.com/zephyrproject-rtos/ci-tools
 * civetweb           99129c5efc907ea613c4b73ccff07581feb58a7a https://github.com/zephyrproject-rtos/civetweb
 * fatfs              13697783bf653dfdf17c57129ce8e181634e5970 https://github.com/zephyrproject-rtos/fatfs
 * hal_nordic         b69c5a7c25007fbc111a0cbda6e2a6a945a6ae9a https://github.com/zephyrproject-rtos/hal_nordic
 * hal_st             5b3ec3e182d4310e8943cc34c6c70ae57d9711da https://github.com/zephyrproject-rtos/hal_st
 * libmetal           87e9e7f2c5b4e238236fe703db61ba23e48dc2ef https://github.com/zephyrproject-rtos/libmetal
 * lvgl               928b61c7c8ef5f770f10e6fd36d4fea0cf375b5e https://github.com/zephyrproject-rtos/lvgl
 * mbedtls            4bf099f1254332d16dcd931ccea0a88d24a7d3c7 https://github.com/zephyrproject-rtos/mbedtls
 * net-tools          1c4fdba512b268033a4cf926bddd323866c3261a https://github.com/zephyrproject-rtos/net-tools
 * open-amp           724f7e2a4519d7e1d40ef330042682dea950c991 https://github.com/zephyrproject-rtos/open-amp
 * loramac-node       170a2579dd890f78f5056f0959cdb9c9bea259a1 https://github.com/zephyrproject-rtos/loramac-node
 * openthread         f23165fde96ae8bd710b08c6d77879465ed92cac https://github.com/zephyrproject-rtos/openthread
 * segger             6fcf61606d6012d2c44129edc033f59331e268bc https://github.com/zephyrproject-rtos/segger
 * tinycbor           40daca97b478989884bffb5226e9ab73ca54b8c4 https://github.com/zephyrproject-rtos/tinycbor
 * tinycrypt          3e9a49d2672ec01435ffbf0d788db6d95ef28de0 https://github.com/zephyrproject-rtos/tinycrypt
 * littlefs           9e4498d1c73009acd84bb36036ee5e2869112a6c https://github.com/zephyrproject-rtos/littlefs
 * mipi-sys-t         957d46bc3ce0d5f628f0d525196bb4db207672ee https://github.com/zephyrproject-rtos/mipi-sys-t
 * nrf_hw_models      9e594dace1af29252903938064b8ecb1b8b77678 https://github.com/zephyrproject-rtos/nrf_hw_models
 * edtt               c39888ff74acf421eeff9a7514fa9b172c3373f7 https://github.com/zephyrproject-rtos/edtt
 */


/** ZBOSS build tag */
#define ZBOSS_BUILD_TAG "10_06_2020"

/** ZBOSS build date (UTC) */
#define ZBOSS_BUILD_DATE 20201007

/** ZBOSS build time (UTC) */
#define ZBOSS_BUILD_TIME 104209


#endif /* ZBOSS_BUILD_INFO_H__ */
