/*
 * Copyright (c) 2020 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */
#ifndef ZBOSS_BUILD_INFO_H__
#define ZBOSS_BUILD_INFO_H__

/**
 * This is an autogenerated file.
 * Please use release scripts to update it's contents.
 *
 * Repositories:
 * platform_ncs       5cc5350d76b6e1abfcda44355494e58ee3c5c8fd https://projecttools.nordicsemi.no/bitbucket/scm/ZOI/platform_ncs.git
 * zboss-stack-src    958ed927736f8cbcbe1270b074f738f08045f734 https://projecttools.nordicsemi.no/bitbucket/scm/zoi/zboss_stable
 * zboss-stack-doc    e190d4a637c3c39bdcfb0b3abbbb1425479f2a8e https://projecttools.nordicsemi.no/bitbucket/scm/zoi/zboss_doc
 * nrf                0a4f29c8d141c9bb378e2693db21f3e28dcb340c https://github.com/nrfconnect/sdk-nrf
 * zephyr             240c7b9a691f6bcee824d1b26a40a368a916bb05 https://github.com/nrfconnect/sdk-zephyr
 * mcuboot            132a537bf94044be93240a43b7622b3040bd017e https://github.com/nrfconnect/sdk-mcuboot
 * mbedtls-nrf        cefdd9954bcc92c08ce2ba41d87b57c29b73482b https://github.com/nrfconnect/sdk-mbedtls
 * nrfxlib            2173e3337c494d131c107e8d9ce7af095d5adc7a https://github.com/nrfconnect/sdk-nrfxlib
 * trusted-firmware-m 7d4a7139009c24ffa6edfb7f24fe32090bca0583 https://github.com/nrfconnect/sdk-trusted-firmware-m
 * tfm-mcuboot        4aa516e7281fc6f9a2dce0b0efda9acc580fa254 https://github.com/nrfconnect/sdk-mcuboot
 * matter             80da8ab1c0aa315a6ee2ce6adf448606372b0a2d https://github.com/nrfconnect/sdk-connectedhomeip
 * cjson              c6af068b7f05207b28d68880740e4b9ec1e4b50a https://github.com/nrfconnect/sdk-cjson
 * cmock              9d092898ef26ece140d9225e037274b64d4f851e https://github.com/ThrowTheSwitch/cmock
 * unity              74cde089e65c3435ce9aa87d5c69f4f16b7f6ade https://github.com/ThrowTheSwitch/unity
 * Alexa-Gadgets-Embedded-Sample-Code face92d8c62184832793f518bb1f19379538c5c1 https://github.com/alexa/Alexa-Gadgets-Embedded-Sample-Code
 * zcbor              317d3c6cd6dee23a151a3e7982d8564e7e19b2e2 https://github.com/NordicSemiconductor/zcbor
 * memfault-firmware-sdk b7eea3b5d8e533d04c6bedbb8148938667334b91 https://github.com/memfault/memfault-firmware-sdk
 * canopennode        53d3415c14d60f8f4bfca54bfbc5d5a667d7e724 https://github.com/zephyrproject-rtos/canopennode
 * civetweb           094aeb41bb93e9199d24d665ee43e9e05d6d7b1c https://github.com/zephyrproject-rtos/civetweb
 * cmsis              b0612c97c1401feeb4160add6462c3627fe90fc7 https://github.com/zephyrproject-rtos/cmsis
 * edtt               1fc2e6f7d2a01a01074456f2ef2ccf1f3df7fac1 https://github.com/zephyrproject-rtos/edtt
 * fatfs              9237454a30bcf6e14a89db174e8dbeb8f31831d2 https://github.com/zephyrproject-rtos/fatfs
 * hal_nordic         626e3dd960a956993441f2ed4bf2db0b5f35f01a https://github.com/zephyrproject-rtos/hal_nordic
 * hal_st             575de9d461aa6f430cf62c58a053675377e700f3 https://github.com/zephyrproject-rtos/hal_st
 * libmetal           f237c9d420a51cc43bc37d744e41191ad613f348 https://github.com/zephyrproject-rtos/libmetal
 * littlefs           7b2cf4ba759bd530b543644e2790b07cf20cd6aa https://github.com/zephyrproject-rtos/littlefs
 * loramac-node       12019623bbad9eb54fe51066847a7cbd4b4eac57 https://github.com/zephyrproject-rtos/loramac-node
 * lvgl               aae1c11102138cf596687e662c0d54b72f72bf9b https://github.com/zephyrproject-rtos/lvgl
 * lz4                8e303c264fc21c2116dc612658003a22e933124d https://github.com/zephyrproject-rtos/lz4
 * mbedtls            3e3e58a92de76069730c63e0d524f40fea948a61 https://github.com/zephyrproject-rtos/mbedtls
 * mipi-sys-t         d9da086b11cda494d85f4d8a9829f505c2d5e380 https://github.com/zephyrproject-rtos/mipi-sys-t
 * nanopb             d148bd26718e4c10414f07a7eb1bd24c62e56c5d https://github.com/zephyrproject-rtos/nanopb
 * net-tools          f49bd1354616fae4093bf36e5eaee43c51a55127 https://github.com/zephyrproject-rtos/net-tools
 * nrf_hw_models      b8cea37dbdc8fc58cc14b4e19fa850877a9da520 https://github.com/zephyrproject-rtos/nrf_hw_models
 * open-amp           cfd050ff38a9d028dc211690b2ec35971128e45e https://github.com/zephyrproject-rtos/open-amp
 * openthread         d4d46ba94290bcf93cc849b832f0ad305c72c473 https://github.com/zephyrproject-rtos/openthread
 * segger             3a52ab222133193802d3c3b4d21730b9b1f1d2f6 https://github.com/zephyrproject-rtos/segger
 * tinycbor           40daca97b478989884bffb5226e9ab73ca54b8c4 https://github.com/zephyrproject-rtos/tinycbor
 * tinycrypt          3e9a49d2672ec01435ffbf0d788db6d95ef28de0 https://github.com/zephyrproject-rtos/tinycrypt
 * TraceRecorderSource e8ca3b6a83d19b2fc4738a0d9607190436e5e452 https://github.com/zephyrproject-rtos/TraceRecorderSource
 * tf-m-tests         52814181f0fde6d1422fac204d42cde30c62e40e https://github.com/zephyrproject-rtos/tf-m-tests
 * psa-arch-tests     0aab24602cbef30f6422e7ef1066a8473073e586 https://github.com/zephyrproject-rtos/psa-arch-tests
 * zscilib            12bfe3f0a9fcbfe3edab7eabc9678b6c62875d34 https://github.com/zephyrproject-rtos/zscilib
 */


/** ZBOSS build tag */
#define ZBOSS_BUILD_TAG "ncs_release-3.12.1.0"

/** ZBOSS platform build tag */
#define ZBOSS_PLATFORM_BUILD_TAG "v3.12.1.0+v5.2.0"

/** ZBOSS build date (UTC) */
#define ZBOSS_BUILD_DATE 20220428

/** ZBOSS build time (UTC) */
#define ZBOSS_BUILD_TIME 100834


#endif /* ZBOSS_BUILD_INFO_H__ */
