extends: substitution
message: "Use '%s' instead of '%s'."
## missingdoc
link: https://docs.microsoft.com/en-us/style-guide/word-choice/use-us-spelling-avoid-non-english-words
# To match “E.g.” and “e.g.”
ignorecase: true
level: error
nonword: true
action:
  name: replace
swap:
  '\b(?:eg|e\.g\.)[\s,]': for example
  # To match only "i.e.", not "ie"
  '\bi\.e\.(?=[\s,])': that is
  '\b(?:viz\.)[\s,]': namely
  '\b(?:ergo)[\s,]': therefore
